#!/bin/fish
# vim:filetype=fish

if test (count $argv) -eq 2
  cd ~/Documents/dotfiles/home/.config/fish/conf.d
  echo "alias $argv[1]=\"$argv[2]\"" >> 02_alias.fish
  git add 02_alias.fish
  git commit -m "add $argv[1] alias"
  git pull
  git push
else
  echo "argv[1]: alias and argv[2]: cmd"
end

