#!/usr/bin/bash

if [ -z "$WAYLAND_DISPLAY" ]; then
  B='#00000000' # blank
  C='#ffffff22' # clear ish
  D='#282828ff' # default
  T='#1d2021ff' # text
  W='#880000ff' # wrong
  V='#fb4934ff' # verifying
  amixer sset Master mute
  i3lock -e \
    --insidever-color=$C \
    --ringver-color=$V \
    --insidewrong-color=$C \
    --ringwrong-color=$W \
    --inside-color=$B \
    --ring-color=$D \
    --line-color=$B \
    --separator-color=$D \
    --verif-color=$T \
    --wrong-color=$T \
    --time-color=$T \
    --date-color=$T \
    --layout-color=$T \
    --keyhl-color=$W \
    --bshl-color=$W \
    --screen \
    1 \
    --blur \
    3 \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A, %m %Y" \
    --verif-text="Wait for it" \
    --wrong-text="70 iq"
else
  image=$(mktemp)
  grim $image
  convert $image -blur 0x1 $image
  swaylock -i -f $image "$@"
  rm -f $image
fi
