#!/bin/fish
# vim:filetype=fish

if test (count $argv) -eq 1
  cd ~/.config/fish/conf.d
  sed -i "/alias $argv[1]/d" 02_alias.fish
  git add 02_alias.fish
  git commit -m "remove $argv[1] alias"
  git pull
  git push
else
  echo "argv[1]: alias"
end

