#!/usr/bin/python3

from time import sleep
from urllib import request
from json import loads
from pathlib import Path

# https://darksky.net/dev/account
weather_api_key_path = f"{str(Path.home())}/weather.key"
with open(weather_api_key_path, 'r') as file:
    api_key = file.read().strip()

weather_file = "/tmp/weather"
with open(weather_file, "w") as f:
    f.write("")

icons = {
    "clear-day": "",
    "clear-night": "",
    "rain": "",
    "snow": "",
    "sleet": "",
    "wind": "",
    "fog": "",
    "cloudy": "",
    "partly-cloudy-day": "",
    "partly-cloudy-night": "",
    "hail": "",
    "thunderstorm": "",
    "tornado": ""
}


location = request.urlopen("https://ipinfo.io/loc", timeout=10).read().decode("utf-8").strip()
query = f"https://api.darksky.net/forecast/{api_key}/{location}?units=ca&exclude=minutely,hourly,daily,flags"
raw_weather_info = loads(request.urlopen(query).read())
current_weather_info = raw_weather_info["currently"]

icon = icons[current_weather_info["icon"]]
temperature = f'{current_weather_info["temperature"]:3.1f}°C'
feels_like = f'{current_weather_info["apparentTemperature"]:3.1f}°C'

print(f"{icon} {temperature}/{feels_like}")
